---
- name: Installing Satellite Server
  hosts: "{{ targethost }}"
  remote_user: root

#  vars_prompt:
#    - name: "username"
#      prompt: "Enter RHN username"
#      private: no
#
#    - name: "password"
#      prompt: "Enter RHN password"
#      private: yes
#
#    - name: "poolid1"
#      prompt: "Enter Employee SKU poolid"
#      private: no
#
#    - name: "poolid2"
#      prompt: "Enter Satellite poolid"
#      private: no
#
#    - name: "organization"
#      prompt: "Enter Default organization name(ExampleCorp)"
#      default: "ExampleCorp"
#      private: no
#
#    - name: "location"
#      prompt: "Enter default location name(India)"
#      default: "India"
#      private: no


  tasks:
    - name: Checking Connection 
      ping:
        
    - name: Registering and Subscribing System
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        pool_ids:
          - "{{ poolid1 }}"
          - "{{ poolid2 }}"

    - name: Disabling Repositories
      command: subscription-manager repos --disable "*"

    - name: Enabling Required Repos
      command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.3-rpms --enable=rhel-7-server-satellite-6.3-puppet4-rpms

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: install the latest version of Apache
      yum:
        name: satellite
        state: latest

    - name: 
      command: satellite-installer --scenario satellite --foreman-initial-organization "{{ organization }}" --foreman-initial-location "{{ location }}" --foreman-admin-username admin --foreman-admin-password changeme 