---
- name: Installing Satellite Server
  hosts: "{{ targethost }}"
  remote_user: root



  tasks:
    - name: Checking Connection 
      ping:
        
    - name: Registering and Subscribing System
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        pool_ids:
          - "{{ poolid1 }}"
          - "{{ poolid2 }}"

    - name: Disabling Repositories
      command: subscription-manager repos --disable "*"

    - name: Enabling Required Repos 
      command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.2-rpms
      when: version == "6.2"

    - name: Enabling Required Repos
      command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.3-rpms --enable=rhel-7-server-satellite-6.3-puppet4-rpms
      when: version == "6.3"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: install the Satellite
      yum:
        name: satellite
        state: latest

    - name: Configuring Satellite Server
      command: satellite-installer --scenario satellite --foreman-initial-organization "{{ organization }}" --foreman-initial-location "{{ location }}" --foreman-admin-username admin --foreman-admin-password changeme 

    - name: Adding firewall rule
      firewalld:
        service: RH-Satellite-6
        permanent: true
        state: enabled
      notify: restart firewalld

  handlers:
    - name: restart firewalld
      service: 
        name: firewalld 
        state: restarted