---
- name: Installing Satellite Server
  hosts: "{{ targethost }}"
  remote_user: root



  tasks:
    - name: Checking Connection 
      ping:
        
    - name: Registering and Subscribing System
      redhat_subscription:
        state: present
        username: "{{ username }}"
        password: "{{ password }}"
        pool_ids:
          - "{{ poolid1 }}"

    - name: Disabling Repositories
      command: subscription-manager repos --disable "*"

    - name: Enabling Required Repos for 5.7 
      command: subscription-manager repos --enable rhel-6-server-rpms
      when: version == "5.7"  

    - name: Enabling Required Repos for 6.2
      command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.2-rpms
      when: version == "6.2"

    - name: Enabling Required Repos for 6.3
      command: subscription-manager repos --enable=rhel-7-server-rpms --enable=rhel-server-rhscl-7-rpms --enable=rhel-7-server-satellite-6.3-rpms --enable=rhel-7-server-satellite-6.3-puppet4-rpms
      when: version == "6.3"

    - name: install the 'BASE' package group
      yum:
        name: "@base"
        state: present
      when: version == "5.7" 

    - name: Copying satellite 5.7 ISO 
      copy:
        src: /satellite-5.7.0-20150108-rhel-6-x86_64.iso
        dest: /satellite-5.7.0-20150108-rhel-6-x86_64.iso
        owner: root
        group: root
        mode: 0777
      when: version == "5.7"

    - name: Copying satellite 5.7 certs
      copy:
        src: /satellite-5.7.example.com.xml
        dest: /satellite-5.7.example.com.xml
        owner: root
        group: root
        mode: 0777
      when: version == "5.7"

    - name: Mounting satellite 5.7 ISO
      command: mount -o loop /satellite-5.7.0-20150108-rhel-6-x86_64.iso /mnt
      when: version == "5.7"

    - name: Copying satellite 5.7 certs
      copy:
        src: /answers.txt
        dest: /tmp/answers.txt
        owner: root
        group: root
        mode: 0777
      when: version == "5.7"

    - name: Installing satellite 5.7 wait back and relax.
      command: perl /mnt/install.pl --answer-file=/tmp/answers.txt
      when: version == "5.7"

    - name: Stoping iptables 
      command: service iptables stop
      when: version == "5.7"


    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
      when: version == "6.2" or version == "6.3"


    - name: install the Satellite
      yum:
        name: satellite
        state: latest
      when: version == "6.2" or version == "6.3"

    - name: Configuring Satellite Server
      command: satellite-installer --scenario satellite --foreman-initial-organization "{{ organization }}" --foreman-initial-location "{{ location }}" --foreman-admin-username admin --foreman-admin-password changeme 
      when: version == "6.2" or version == "6.3"


    - name: Adding firewall rule
      firewalld:
        service: RH-Satellite-6
        permanent: true
        state: enabled
      notify: restart firewalld
      when: version == "6.2" or version == "6.3"

  handlers:
    - name: restart firewalld
      service: 
        name: firewalld 
        state: restarted